# Generated by Django 3.0.5 on 2020-04-12 12:49

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommentLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('avatar', models.FileField(default='AVATAR.png', upload_to='')),
                ('comment', models.TextField()),
                ('like', models.IntegerField(default=1)),
                ('created_at', models.DateField(blank=True, default=datetime.datetime(2020, 4, 12, 12, 49, 36, 610534, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 12, 12, 49, 36, 582267, tzinfo=utc))),
                ('bio', models.TextField(blank=True, null=True)),
                ('avatar', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=50)),
                ('tags', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('created_at', models.DateField(blank=True, default=datetime.datetime(2020, 4, 12, 12, 49, 36, 609768, tzinfo=utc))),
                ('like', models.IntegerField(default=0)),
                ('fullname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dribbble_app.User')),
            ],
        ),
    ]
