# Generated by Django 3.0.5 on 2020-04-11 14:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dribbble_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 11, 14, 0, 4, 925986, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userdesign',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 4, 11, 14, 0, 4, 953936, tzinfo=utc)),
        ),
    ]
