# Generated by Django 3.0.5 on 2020-04-12 12:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dribbble_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentlike',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 4, 12, 12, 50, 9, 452856, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='design',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 4, 12, 12, 50, 9, 452032, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 12, 12, 50, 9, 423672, tzinfo=utc)),
        ),
    ]
