# Generated by Django 3.0.5 on 2020-04-12 12:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dribbble_app', '0002_auto_20200412_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentlike',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 4, 12, 12, 54, 41, 2097, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='design',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 4, 12, 12, 54, 41, 1329, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 12, 12, 54, 40, 973239, tzinfo=utc)),
        ),
    ]
