# Generated by Django 3.0.5 on 2020-04-12 08:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dribbble_app', '0002_auto_20200411_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designlike',
            name='title',
        ),
        migrations.RemoveField(
            model_name='designlike',
            name='username',
        ),
        migrations.RenameField(
            model_name='commentlike',
            old_name='username_like',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='commentlike',
            name='title',
        ),
        migrations.RemoveField(
            model_name='commentlike',
            name='username',
        ),
        migrations.AddField(
            model_name='commentlike',
            name='avatar',
            field=models.FileField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='commentlike',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 4, 12, 8, 13, 10, 911436, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='commentlike',
            name='comment',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 12, 8, 13, 10, 882578, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userdesign',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 4, 12, 8, 13, 10, 910833, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='DesignComment',
        ),
        migrations.DeleteModel(
            name='DesignLike',
        ),
    ]
