# Generated by Django 3.0.5 on 2020-04-12 10:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dribbble_app', '0003_auto_20200412_0813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdesign',
            name='username',
        ),
        migrations.AlterField(
            model_name='commentlike',
            name='avatar',
            field=models.FileField(default='photo6334774800085527044_6Tw2E3B.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='commentlike',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 4, 12, 10, 5, 48, 182846, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 12, 10, 5, 48, 154162, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userdesign',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 4, 12, 10, 5, 48, 182337, tzinfo=utc)),
        ),
    ]
