# Generated by Django 3.0.5 on 2020-04-12 12:55

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dribbble_app', '0003_auto_20200412_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentlike',
            name='design',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dribbble_app.Design'),
        ),
        migrations.AlterField(
            model_name='commentlike',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 4, 12, 12, 55, 33, 449979, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='design',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 4, 12, 12, 55, 33, 449186, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 12, 12, 55, 33, 421535, tzinfo=utc)),
        ),
    ]
