# Generated by Django 3.0.5 on 2020-04-12 10:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dribbble_app', '0004_auto_20200412_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentlike',
            name='avatar',
            field=models.FileField(default='AVATAR.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='commentlike',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 4, 12, 10, 9, 55, 720628, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 12, 10, 9, 55, 692551, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userdesign',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 4, 12, 10, 9, 55, 720099, tzinfo=utc)),
        ),
    ]
