# Generated by Django 3.0.5 on 2020-04-12 10:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dribbble_app', '0005_auto_20200412_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentlike',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 4, 12, 10, 30, 52, 488892, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 12, 10, 30, 52, 459656, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userdesign',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 4, 12, 10, 30, 52, 488324, tzinfo=utc)),
        ),
    ]
