# Generated by Django 3.0.5 on 2020-04-13 01:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dribbble_app', '0005_auto_20200413_0147'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentlike',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='commentlike',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 4, 13, 1, 48, 34, 744807, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='design',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 4, 13, 1, 48, 34, 743963, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 13, 1, 48, 34, 714798, tzinfo=utc)),
        ),
    ]
